// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"github.com/eyebluecn/sc-misc/src/model/po"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gen/helper"

	"gorm.io/plugin/dbresolver"
)

func newAuthorPO(db *gorm.DB, opts ...gen.DOOption) authorPO {
	_authorPO := authorPO{}

	_authorPO.authorPODo.UseDB(db, opts...)
	_authorPO.authorPODo.UseModel(&po.AuthorPO{})

	tableName := _authorPO.authorPODo.TableName()
	_authorPO.ALL = field.NewAsterisk(tableName)
	_authorPO.ID = field.NewInt64(tableName, "id")
	_authorPO.CreateTime = field.NewTime(tableName, "create_time")
	_authorPO.UpdateTime = field.NewTime(tableName, "update_time")
	_authorPO.Username = field.NewString(tableName, "username")
	_authorPO.Password = field.NewString(tableName, "password")
	_authorPO.Realname = field.NewString(tableName, "realname")

	_authorPO.fillFieldMap()

	return _authorPO
}

// authorPO 作者表
type authorPO struct {
	authorPODo authorPODo

	ALL        field.Asterisk
	ID         field.Int64  // 主键
	CreateTime field.Time   // 创建时间
	UpdateTime field.Time   // 更新时间
	Username   field.String // 用户名
	Password   field.String // 密码
	Realname   field.String // 真实姓名

	fieldMap map[string]field.Expr
}

func (a authorPO) Table(newTableName string) *authorPO {
	a.authorPODo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a authorPO) As(alias string) *authorPO {
	a.authorPODo.DO = *(a.authorPODo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *authorPO) updateTableName(table string) *authorPO {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.CreateTime = field.NewTime(table, "create_time")
	a.UpdateTime = field.NewTime(table, "update_time")
	a.Username = field.NewString(table, "username")
	a.Password = field.NewString(table, "password")
	a.Realname = field.NewString(table, "realname")

	a.fillFieldMap()

	return a
}

func (a *authorPO) WithContext(ctx context.Context) *authorPODo { return a.authorPODo.WithContext(ctx) }

func (a authorPO) TableName() string { return a.authorPODo.TableName() }

func (a authorPO) Alias() string { return a.authorPODo.Alias() }

func (a authorPO) Columns(cols ...field.Expr) gen.Columns { return a.authorPODo.Columns(cols...) }

func (a *authorPO) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *authorPO) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.ID
	a.fieldMap["create_time"] = a.CreateTime
	a.fieldMap["update_time"] = a.UpdateTime
	a.fieldMap["username"] = a.Username
	a.fieldMap["password"] = a.Password
	a.fieldMap["realname"] = a.Realname
}

func (a authorPO) clone(db *gorm.DB) authorPO {
	a.authorPODo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a authorPO) replaceDB(db *gorm.DB) authorPO {
	a.authorPODo.ReplaceDB(db)
	return a
}

type authorPODo struct{ gen.DO }

func (a authorPODo) Debug() *authorPODo {
	return a.withDO(a.DO.Debug())
}

func (a authorPODo) WithContext(ctx context.Context) *authorPODo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a authorPODo) ReadDB() *authorPODo {
	return a.Clauses(dbresolver.Read)
}

func (a authorPODo) WriteDB() *authorPODo {
	return a.Clauses(dbresolver.Write)
}

func (a authorPODo) Session(config *gorm.Session) *authorPODo {
	return a.withDO(a.DO.Session(config))
}

func (a authorPODo) Clauses(conds ...clause.Expression) *authorPODo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a authorPODo) Returning(value interface{}, columns ...string) *authorPODo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a authorPODo) Not(conds ...gen.Condition) *authorPODo {
	return a.withDO(a.DO.Not(conds...))
}

func (a authorPODo) Or(conds ...gen.Condition) *authorPODo {
	return a.withDO(a.DO.Or(conds...))
}

func (a authorPODo) Select(conds ...field.Expr) *authorPODo {
	return a.withDO(a.DO.Select(conds...))
}

func (a authorPODo) Where(conds ...gen.Condition) *authorPODo {
	return a.withDO(a.DO.Where(conds...))
}

func (a authorPODo) Order(conds ...field.Expr) *authorPODo {
	return a.withDO(a.DO.Order(conds...))
}

func (a authorPODo) Distinct(cols ...field.Expr) *authorPODo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a authorPODo) Omit(cols ...field.Expr) *authorPODo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a authorPODo) Join(table schema.Tabler, on ...field.Expr) *authorPODo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a authorPODo) LeftJoin(table schema.Tabler, on ...field.Expr) *authorPODo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a authorPODo) RightJoin(table schema.Tabler, on ...field.Expr) *authorPODo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a authorPODo) Group(cols ...field.Expr) *authorPODo {
	return a.withDO(a.DO.Group(cols...))
}

func (a authorPODo) Having(conds ...gen.Condition) *authorPODo {
	return a.withDO(a.DO.Having(conds...))
}

func (a authorPODo) Limit(limit int) *authorPODo {
	return a.withDO(a.DO.Limit(limit))
}

func (a authorPODo) Offset(offset int) *authorPODo {
	return a.withDO(a.DO.Offset(offset))
}

func (a authorPODo) Scopes(funcs ...func(gen.Dao) gen.Dao) *authorPODo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a authorPODo) Unscoped() *authorPODo {
	return a.withDO(a.DO.Unscoped())
}

func (a authorPODo) Create(values ...*po.AuthorPO) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a authorPODo) CreateInBatches(values []*po.AuthorPO, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a authorPODo) Save(values ...*po.AuthorPO) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a authorPODo) First() (*po.AuthorPO, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*po.AuthorPO), nil
	}
}

func (a authorPODo) Take() (*po.AuthorPO, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*po.AuthorPO), nil
	}
}

func (a authorPODo) Last() (*po.AuthorPO, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*po.AuthorPO), nil
	}
}

func (a authorPODo) Find() ([]*po.AuthorPO, error) {
	result, err := a.DO.Find()
	return result.([]*po.AuthorPO), err
}

func (a authorPODo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.AuthorPO, err error) {
	buf := make([]*po.AuthorPO, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a authorPODo) FindInBatches(result *[]*po.AuthorPO, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a authorPODo) Attrs(attrs ...field.AssignExpr) *authorPODo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a authorPODo) Assign(attrs ...field.AssignExpr) *authorPODo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a authorPODo) Joins(fields ...field.RelationField) *authorPODo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a authorPODo) Preload(fields ...field.RelationField) *authorPODo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a authorPODo) FirstOrInit() (*po.AuthorPO, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*po.AuthorPO), nil
	}
}

func (a authorPODo) FirstOrCreate() (*po.AuthorPO, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*po.AuthorPO), nil
	}
}

func (a authorPODo) FindByPage(offset int, limit int) (result []*po.AuthorPO, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a authorPODo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a authorPODo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a authorPODo) Delete(models ...*po.AuthorPO) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *authorPODo) withDO(do gen.Dao) *authorPODo {
	a.DO = *do.(*gen.DO)
	return a
}
