// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gen/helper"

	"gorm.io/plugin/dbresolver"
)

func newContractPO(db *gorm.DB, opts ...gen.DOOption) contractPO {
	_contractPO := contractPO{}

	_contractPO.contractPODo.UseDB(db, opts...)
	_contractPO.contractPODo.UseModel(&po.ContractPO{})

	tableName := _contractPO.contractPODo.TableName()
	_contractPO.ALL = field.NewAsterisk(tableName)
	_contractPO.ID = field.NewInt64(tableName, "id")
	_contractPO.CreateTime = field.NewTime(tableName, "create_time")
	_contractPO.UpdateTime = field.NewTime(tableName, "update_time")
	_contractPO.Name = field.NewString(tableName, "name")
	_contractPO.Content = field.NewString(tableName, "content")
	_contractPO.ColumnID = field.NewInt64(tableName, "column_id")
	_contractPO.AuthorID = field.NewInt64(tableName, "author_id")
	_contractPO.Status = field.NewInt32(tableName, "status")
	_contractPO.Percentage = field.NewFloat64(tableName, "percentage")
	_contractPO.PaymentDay = field.NewString(tableName, "payment_day")

	_contractPO.fillFieldMap()

	return _contractPO
}

// contractPO 作者表
type contractPO struct {
	contractPODo contractPODo

	ALL        field.Asterisk
	ID         field.Int64   // 主键
	CreateTime field.Time    // 创建时间
	UpdateTime field.Time    // 更新时间
	Name       field.String  // 名称
	Content    field.String  // 内容
	ColumnID   field.Int64   // 专栏id
	AuthorID   field.Int64   // 作者id
	Status     field.Int32   // 状态 0/1/2 未生效/已生效/已禁用
	Percentage field.Float64 // 分成比例
	PaymentDay field.String  // 账期日

	fieldMap map[string]field.Expr
}

func (c contractPO) Table(newTableName string) *contractPO {
	c.contractPODo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c contractPO) As(alias string) *contractPO {
	c.contractPODo.DO = *(c.contractPODo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *contractPO) updateTableName(table string) *contractPO {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateTime = field.NewTime(table, "update_time")
	c.Name = field.NewString(table, "name")
	c.Content = field.NewString(table, "content")
	c.ColumnID = field.NewInt64(table, "column_id")
	c.AuthorID = field.NewInt64(table, "author_id")
	c.Status = field.NewInt32(table, "status")
	c.Percentage = field.NewFloat64(table, "percentage")
	c.PaymentDay = field.NewString(table, "payment_day")

	c.fillFieldMap()

	return c
}

func (c *contractPO) WithContext(ctx context.Context) *contractPODo {
	return c.contractPODo.WithContext(ctx)
}

func (c contractPO) TableName() string { return c.contractPODo.TableName() }

func (c contractPO) Alias() string { return c.contractPODo.Alias() }

func (c contractPO) Columns(cols ...field.Expr) gen.Columns { return c.contractPODo.Columns(cols...) }

func (c *contractPO) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *contractPO) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 10)
	c.fieldMap["id"] = c.ID
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_time"] = c.UpdateTime
	c.fieldMap["name"] = c.Name
	c.fieldMap["content"] = c.Content
	c.fieldMap["column_id"] = c.ColumnID
	c.fieldMap["author_id"] = c.AuthorID
	c.fieldMap["status"] = c.Status
	c.fieldMap["percentage"] = c.Percentage
	c.fieldMap["payment_day"] = c.PaymentDay
}

func (c contractPO) clone(db *gorm.DB) contractPO {
	c.contractPODo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c contractPO) replaceDB(db *gorm.DB) contractPO {
	c.contractPODo.ReplaceDB(db)
	return c
}

type contractPODo struct{ gen.DO }

func (c contractPODo) Debug() *contractPODo {
	return c.withDO(c.DO.Debug())
}

func (c contractPODo) WithContext(ctx context.Context) *contractPODo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c contractPODo) ReadDB() *contractPODo {
	return c.Clauses(dbresolver.Read)
}

func (c contractPODo) WriteDB() *contractPODo {
	return c.Clauses(dbresolver.Write)
}

func (c contractPODo) Session(config *gorm.Session) *contractPODo {
	return c.withDO(c.DO.Session(config))
}

func (c contractPODo) Clauses(conds ...clause.Expression) *contractPODo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c contractPODo) Returning(value interface{}, columns ...string) *contractPODo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c contractPODo) Not(conds ...gen.Condition) *contractPODo {
	return c.withDO(c.DO.Not(conds...))
}

func (c contractPODo) Or(conds ...gen.Condition) *contractPODo {
	return c.withDO(c.DO.Or(conds...))
}

func (c contractPODo) Select(conds ...field.Expr) *contractPODo {
	return c.withDO(c.DO.Select(conds...))
}

func (c contractPODo) Where(conds ...gen.Condition) *contractPODo {
	return c.withDO(c.DO.Where(conds...))
}

func (c contractPODo) Order(conds ...field.Expr) *contractPODo {
	return c.withDO(c.DO.Order(conds...))
}

func (c contractPODo) Distinct(cols ...field.Expr) *contractPODo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c contractPODo) Omit(cols ...field.Expr) *contractPODo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c contractPODo) Join(table schema.Tabler, on ...field.Expr) *contractPODo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c contractPODo) LeftJoin(table schema.Tabler, on ...field.Expr) *contractPODo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c contractPODo) RightJoin(table schema.Tabler, on ...field.Expr) *contractPODo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c contractPODo) Group(cols ...field.Expr) *contractPODo {
	return c.withDO(c.DO.Group(cols...))
}

func (c contractPODo) Having(conds ...gen.Condition) *contractPODo {
	return c.withDO(c.DO.Having(conds...))
}

func (c contractPODo) Limit(limit int) *contractPODo {
	return c.withDO(c.DO.Limit(limit))
}

func (c contractPODo) Offset(offset int) *contractPODo {
	return c.withDO(c.DO.Offset(offset))
}

func (c contractPODo) Scopes(funcs ...func(gen.Dao) gen.Dao) *contractPODo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c contractPODo) Unscoped() *contractPODo {
	return c.withDO(c.DO.Unscoped())
}

func (c contractPODo) Create(values ...*po.ContractPO) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c contractPODo) CreateInBatches(values []*po.ContractPO, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c contractPODo) Save(values ...*po.ContractPO) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c contractPODo) First() (*po.ContractPO, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*po.ContractPO), nil
	}
}

func (c contractPODo) Take() (*po.ContractPO, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*po.ContractPO), nil
	}
}

func (c contractPODo) Last() (*po.ContractPO, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*po.ContractPO), nil
	}
}

func (c contractPODo) Find() ([]*po.ContractPO, error) {
	result, err := c.DO.Find()
	return result.([]*po.ContractPO), err
}

func (c contractPODo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.ContractPO, err error) {
	buf := make([]*po.ContractPO, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c contractPODo) FindInBatches(result *[]*po.ContractPO, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c contractPODo) Attrs(attrs ...field.AssignExpr) *contractPODo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c contractPODo) Assign(attrs ...field.AssignExpr) *contractPODo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c contractPODo) Joins(fields ...field.RelationField) *contractPODo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c contractPODo) Preload(fields ...field.RelationField) *contractPODo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c contractPODo) FirstOrInit() (*po.ContractPO, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*po.ContractPO), nil
	}
}

func (c contractPODo) FirstOrCreate() (*po.ContractPO, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*po.ContractPO), nil
	}
}

func (c contractPODo) FindByPage(offset int, limit int) (result []*po.ContractPO, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c contractPODo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c contractPODo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c contractPODo) Delete(models ...*po.ContractPO) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *contractPODo) withDO(do gen.Dao) *contractPODo {
	c.DO = *do.(*gen.DO)
	return c
}
