// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/eyebluecn/sc-misc/src/repository/db_model"
)

func newPaymentDO(db *gorm.DB, opts ...gen.DOOption) paymentDO {
	_paymentDO := paymentDO{}

	_paymentDO.paymentDODo.UseDB(db, opts...)
	_paymentDO.paymentDODo.UseModel(&db_model.PaymentDO{})

	tableName := _paymentDO.paymentDODo.TableName()
	_paymentDO.ALL = field.NewAsterisk(tableName)
	_paymentDO.ID = field.NewInt64(tableName, "id")
	_paymentDO.CreateTime = field.NewTime(tableName, "create_time")
	_paymentDO.UpdateTime = field.NewTime(tableName, "update_time")
	_paymentDO.OrderNo = field.NewString(tableName, "order_no")
	_paymentDO.Method = field.NewString(tableName, "method")
	_paymentDO.ThirdTransactionNo = field.NewString(tableName, "third_transaction_no")
	_paymentDO.Amount = field.NewInt64(tableName, "amount")
	_paymentDO.Status = field.NewInt32(tableName, "status")

	_paymentDO.fillFieldMap()

	return _paymentDO
}

// paymentDO 支付单，用户支付给平台的单据
type paymentDO struct {
	paymentDODo paymentDODo

	ALL                field.Asterisk
	ID                 field.Int64  // 主键
	CreateTime         field.Time   // 创建时间
	UpdateTime         field.Time   // 更新时间
	OrderNo            field.String // 订单编号
	Method             field.String // 支付方式 ALIPAY/WEIXIN 支付宝/微信
	ThirdTransactionNo field.String // 支付平台订单号
	Amount             field.Int64  // 金额(单位：分)
	Status             field.Int32  // 支付状态 0/1/2  未支付/已支付/已关闭

	fieldMap map[string]field.Expr
}

func (p paymentDO) Table(newTableName string) *paymentDO {
	p.paymentDODo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentDO) As(alias string) *paymentDO {
	p.paymentDODo.DO = *(p.paymentDODo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentDO) updateTableName(table string) *paymentDO {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.CreateTime = field.NewTime(table, "create_time")
	p.UpdateTime = field.NewTime(table, "update_time")
	p.OrderNo = field.NewString(table, "order_no")
	p.Method = field.NewString(table, "method")
	p.ThirdTransactionNo = field.NewString(table, "third_transaction_no")
	p.Amount = field.NewInt64(table, "amount")
	p.Status = field.NewInt32(table, "status")

	p.fillFieldMap()

	return p
}

func (p *paymentDO) WithContext(ctx context.Context) *paymentDODo {
	return p.paymentDODo.WithContext(ctx)
}

func (p paymentDO) TableName() string { return p.paymentDODo.TableName() }

func (p paymentDO) Alias() string { return p.paymentDODo.Alias() }

func (p paymentDO) Columns(cols ...field.Expr) gen.Columns { return p.paymentDODo.Columns(cols...) }

func (p *paymentDO) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentDO) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 8)
	p.fieldMap["id"] = p.ID
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["update_time"] = p.UpdateTime
	p.fieldMap["order_no"] = p.OrderNo
	p.fieldMap["method"] = p.Method
	p.fieldMap["third_transaction_no"] = p.ThirdTransactionNo
	p.fieldMap["amount"] = p.Amount
	p.fieldMap["status"] = p.Status
}

func (p paymentDO) clone(db *gorm.DB) paymentDO {
	p.paymentDODo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentDO) replaceDB(db *gorm.DB) paymentDO {
	p.paymentDODo.ReplaceDB(db)
	return p
}

type paymentDODo struct{ gen.DO }

func (p paymentDODo) Debug() *paymentDODo {
	return p.withDO(p.DO.Debug())
}

func (p paymentDODo) WithContext(ctx context.Context) *paymentDODo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentDODo) ReadDB() *paymentDODo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentDODo) WriteDB() *paymentDODo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentDODo) Session(config *gorm.Session) *paymentDODo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentDODo) Clauses(conds ...clause.Expression) *paymentDODo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentDODo) Returning(value interface{}, columns ...string) *paymentDODo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentDODo) Not(conds ...gen.Condition) *paymentDODo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentDODo) Or(conds ...gen.Condition) *paymentDODo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentDODo) Select(conds ...field.Expr) *paymentDODo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentDODo) Where(conds ...gen.Condition) *paymentDODo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentDODo) Order(conds ...field.Expr) *paymentDODo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentDODo) Distinct(cols ...field.Expr) *paymentDODo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentDODo) Omit(cols ...field.Expr) *paymentDODo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentDODo) Join(table schema.Tabler, on ...field.Expr) *paymentDODo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentDODo) LeftJoin(table schema.Tabler, on ...field.Expr) *paymentDODo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentDODo) RightJoin(table schema.Tabler, on ...field.Expr) *paymentDODo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentDODo) Group(cols ...field.Expr) *paymentDODo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentDODo) Having(conds ...gen.Condition) *paymentDODo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentDODo) Limit(limit int) *paymentDODo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentDODo) Offset(offset int) *paymentDODo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentDODo) Scopes(funcs ...func(gen.Dao) gen.Dao) *paymentDODo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentDODo) Unscoped() *paymentDODo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentDODo) Create(values ...*db_model.PaymentDO) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentDODo) CreateInBatches(values []*db_model.PaymentDO, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentDODo) Save(values ...*db_model.PaymentDO) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentDODo) First() (*db_model.PaymentDO, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.PaymentDO), nil
	}
}

func (p paymentDODo) Take() (*db_model.PaymentDO, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.PaymentDO), nil
	}
}

func (p paymentDODo) Last() (*db_model.PaymentDO, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.PaymentDO), nil
	}
}

func (p paymentDODo) Find() ([]*db_model.PaymentDO, error) {
	result, err := p.DO.Find()
	return result.([]*db_model.PaymentDO), err
}

func (p paymentDODo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*db_model.PaymentDO, err error) {
	buf := make([]*db_model.PaymentDO, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentDODo) FindInBatches(result *[]*db_model.PaymentDO, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentDODo) Attrs(attrs ...field.AssignExpr) *paymentDODo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentDODo) Assign(attrs ...field.AssignExpr) *paymentDODo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentDODo) Joins(fields ...field.RelationField) *paymentDODo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentDODo) Preload(fields ...field.RelationField) *paymentDODo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentDODo) FirstOrInit() (*db_model.PaymentDO, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.PaymentDO), nil
	}
}

func (p paymentDODo) FirstOrCreate() (*db_model.PaymentDO, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.PaymentDO), nil
	}
}

func (p paymentDODo) FindByPage(offset int, limit int) (result []*db_model.PaymentDO, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentDODo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentDODo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentDODo) Delete(models ...*db_model.PaymentDO) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentDODo) withDO(do gen.Dao) *paymentDODo {
	p.DO = *do.(*gen.DO)
	return p
}
