// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/eyebluecn/sc-misc/src/repository/db_model"
)

func newColumnQuoteDO(db *gorm.DB, opts ...gen.DOOption) columnQuoteDO {
	_columnQuoteDO := columnQuoteDO{}

	_columnQuoteDO.columnQuoteDODo.UseDB(db, opts...)
	_columnQuoteDO.columnQuoteDODo.UseModel(&db_model.ColumnQuoteDO{})

	tableName := _columnQuoteDO.columnQuoteDODo.TableName()
	_columnQuoteDO.ALL = field.NewAsterisk(tableName)
	_columnQuoteDO.ID = field.NewInt64(tableName, "id")
	_columnQuoteDO.CreateTime = field.NewTime(tableName, "create_time")
	_columnQuoteDO.UpdateTime = field.NewTime(tableName, "update_time")
	_columnQuoteDO.ColumnID = field.NewInt64(tableName, "column_id")
	_columnQuoteDO.EditorID = field.NewInt64(tableName, "editor_id")
	_columnQuoteDO.Price = field.NewInt64(tableName, "price")
	_columnQuoteDO.Status = field.NewInt32(tableName, "status")

	_columnQuoteDO.fillFieldMap()

	return _columnQuoteDO
}

// columnQuoteDO 专栏报价表
type columnQuoteDO struct {
	columnQuoteDODo columnQuoteDODo

	ALL        field.Asterisk
	ID         field.Int64 // 主键
	CreateTime field.Time  // 创建时间
	UpdateTime field.Time  // 更新时间
	ColumnID   field.Int64 // 专栏id
	EditorID   field.Int64 // 编辑id
	Price      field.Int64 // 价格（单位：分）
	Status     field.Int32 // 报价状态 0/1  未生效/已生效

	fieldMap map[string]field.Expr
}

func (c columnQuoteDO) Table(newTableName string) *columnQuoteDO {
	c.columnQuoteDODo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c columnQuoteDO) As(alias string) *columnQuoteDO {
	c.columnQuoteDODo.DO = *(c.columnQuoteDODo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *columnQuoteDO) updateTableName(table string) *columnQuoteDO {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateTime = field.NewTime(table, "update_time")
	c.ColumnID = field.NewInt64(table, "column_id")
	c.EditorID = field.NewInt64(table, "editor_id")
	c.Price = field.NewInt64(table, "price")
	c.Status = field.NewInt32(table, "status")

	c.fillFieldMap()

	return c
}

func (c *columnQuoteDO) WithContext(ctx context.Context) *columnQuoteDODo {
	return c.columnQuoteDODo.WithContext(ctx)
}

func (c columnQuoteDO) TableName() string { return c.columnQuoteDODo.TableName() }

func (c columnQuoteDO) Alias() string { return c.columnQuoteDODo.Alias() }

func (c columnQuoteDO) Columns(cols ...field.Expr) gen.Columns {
	return c.columnQuoteDODo.Columns(cols...)
}

func (c *columnQuoteDO) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *columnQuoteDO) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["id"] = c.ID
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_time"] = c.UpdateTime
	c.fieldMap["column_id"] = c.ColumnID
	c.fieldMap["editor_id"] = c.EditorID
	c.fieldMap["price"] = c.Price
	c.fieldMap["status"] = c.Status
}

func (c columnQuoteDO) clone(db *gorm.DB) columnQuoteDO {
	c.columnQuoteDODo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c columnQuoteDO) replaceDB(db *gorm.DB) columnQuoteDO {
	c.columnQuoteDODo.ReplaceDB(db)
	return c
}

type columnQuoteDODo struct{ gen.DO }

func (c columnQuoteDODo) Debug() *columnQuoteDODo {
	return c.withDO(c.DO.Debug())
}

func (c columnQuoteDODo) WithContext(ctx context.Context) *columnQuoteDODo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c columnQuoteDODo) ReadDB() *columnQuoteDODo {
	return c.Clauses(dbresolver.Read)
}

func (c columnQuoteDODo) WriteDB() *columnQuoteDODo {
	return c.Clauses(dbresolver.Write)
}

func (c columnQuoteDODo) Session(config *gorm.Session) *columnQuoteDODo {
	return c.withDO(c.DO.Session(config))
}

func (c columnQuoteDODo) Clauses(conds ...clause.Expression) *columnQuoteDODo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c columnQuoteDODo) Returning(value interface{}, columns ...string) *columnQuoteDODo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c columnQuoteDODo) Not(conds ...gen.Condition) *columnQuoteDODo {
	return c.withDO(c.DO.Not(conds...))
}

func (c columnQuoteDODo) Or(conds ...gen.Condition) *columnQuoteDODo {
	return c.withDO(c.DO.Or(conds...))
}

func (c columnQuoteDODo) Select(conds ...field.Expr) *columnQuoteDODo {
	return c.withDO(c.DO.Select(conds...))
}

func (c columnQuoteDODo) Where(conds ...gen.Condition) *columnQuoteDODo {
	return c.withDO(c.DO.Where(conds...))
}

func (c columnQuoteDODo) Order(conds ...field.Expr) *columnQuoteDODo {
	return c.withDO(c.DO.Order(conds...))
}

func (c columnQuoteDODo) Distinct(cols ...field.Expr) *columnQuoteDODo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c columnQuoteDODo) Omit(cols ...field.Expr) *columnQuoteDODo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c columnQuoteDODo) Join(table schema.Tabler, on ...field.Expr) *columnQuoteDODo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c columnQuoteDODo) LeftJoin(table schema.Tabler, on ...field.Expr) *columnQuoteDODo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c columnQuoteDODo) RightJoin(table schema.Tabler, on ...field.Expr) *columnQuoteDODo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c columnQuoteDODo) Group(cols ...field.Expr) *columnQuoteDODo {
	return c.withDO(c.DO.Group(cols...))
}

func (c columnQuoteDODo) Having(conds ...gen.Condition) *columnQuoteDODo {
	return c.withDO(c.DO.Having(conds...))
}

func (c columnQuoteDODo) Limit(limit int) *columnQuoteDODo {
	return c.withDO(c.DO.Limit(limit))
}

func (c columnQuoteDODo) Offset(offset int) *columnQuoteDODo {
	return c.withDO(c.DO.Offset(offset))
}

func (c columnQuoteDODo) Scopes(funcs ...func(gen.Dao) gen.Dao) *columnQuoteDODo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c columnQuoteDODo) Unscoped() *columnQuoteDODo {
	return c.withDO(c.DO.Unscoped())
}

func (c columnQuoteDODo) Create(values ...*db_model.ColumnQuoteDO) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c columnQuoteDODo) CreateInBatches(values []*db_model.ColumnQuoteDO, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c columnQuoteDODo) Save(values ...*db_model.ColumnQuoteDO) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c columnQuoteDODo) First() (*db_model.ColumnQuoteDO, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.ColumnQuoteDO), nil
	}
}

func (c columnQuoteDODo) Take() (*db_model.ColumnQuoteDO, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.ColumnQuoteDO), nil
	}
}

func (c columnQuoteDODo) Last() (*db_model.ColumnQuoteDO, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.ColumnQuoteDO), nil
	}
}

func (c columnQuoteDODo) Find() ([]*db_model.ColumnQuoteDO, error) {
	result, err := c.DO.Find()
	return result.([]*db_model.ColumnQuoteDO), err
}

func (c columnQuoteDODo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*db_model.ColumnQuoteDO, err error) {
	buf := make([]*db_model.ColumnQuoteDO, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c columnQuoteDODo) FindInBatches(result *[]*db_model.ColumnQuoteDO, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c columnQuoteDODo) Attrs(attrs ...field.AssignExpr) *columnQuoteDODo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c columnQuoteDODo) Assign(attrs ...field.AssignExpr) *columnQuoteDODo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c columnQuoteDODo) Joins(fields ...field.RelationField) *columnQuoteDODo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c columnQuoteDODo) Preload(fields ...field.RelationField) *columnQuoteDODo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c columnQuoteDODo) FirstOrInit() (*db_model.ColumnQuoteDO, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.ColumnQuoteDO), nil
	}
}

func (c columnQuoteDODo) FirstOrCreate() (*db_model.ColumnQuoteDO, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.ColumnQuoteDO), nil
	}
}

func (c columnQuoteDODo) FindByPage(offset int, limit int) (result []*db_model.ColumnQuoteDO, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c columnQuoteDODo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c columnQuoteDODo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c columnQuoteDODo) Delete(models ...*db_model.ColumnQuoteDO) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *columnQuoteDODo) withDO(do gen.Dao) *columnQuoteDODo {
	c.DO = *do.(*gen.DO)
	return c
}
