// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gen/helper"

	"gorm.io/plugin/dbresolver"
)

func newReceiptPO(db *gorm.DB, opts ...gen.DOOption) receiptPO {
	_receiptPO := receiptPO{}

	_receiptPO.receiptPODo.UseDB(db, opts...)
	_receiptPO.receiptPODo.UseModel(&po.ReceiptPO{})

	tableName := _receiptPO.receiptPODo.TableName()
	_receiptPO.ALL = field.NewAsterisk(tableName)
	_receiptPO.ID = field.NewInt64(tableName, "id")
	_receiptPO.CreateTime = field.NewTime(tableName, "create_time")
	_receiptPO.UpdateTime = field.NewTime(tableName, "update_time")
	_receiptPO.OrderNo = field.NewString(tableName, "order_no")
	_receiptPO.Method = field.NewString(tableName, "method")
	_receiptPO.ThirdTransactionNo = field.NewString(tableName, "third_transaction_no")
	_receiptPO.Amount = field.NewInt64(tableName, "amount")
	_receiptPO.Status = field.NewInt32(tableName, "status")

	_receiptPO.fillFieldMap()

	return _receiptPO
}

// receiptPO 收款单，作者从平台收款的单据
type receiptPO struct {
	receiptPODo receiptPODo

	ALL                field.Asterisk
	ID                 field.Int64  // 主键
	CreateTime         field.Time   // 创建时间
	UpdateTime         field.Time   // 更新时间
	OrderNo            field.String // 订单编号
	Method             field.String // 收款方式 ALIPAY/WEIXIN 支付宝/微信
	ThirdTransactionNo field.String // 收款平台订单号
	Amount             field.Int64  // 金额(单位：分)
	Status             field.Int32  // 支付状态 0/1/2 未收款/已收款/已关闭

	fieldMap map[string]field.Expr
}

func (r receiptPO) Table(newTableName string) *receiptPO {
	r.receiptPODo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r receiptPO) As(alias string) *receiptPO {
	r.receiptPODo.DO = *(r.receiptPODo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *receiptPO) updateTableName(table string) *receiptPO {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.CreateTime = field.NewTime(table, "create_time")
	r.UpdateTime = field.NewTime(table, "update_time")
	r.OrderNo = field.NewString(table, "order_no")
	r.Method = field.NewString(table, "method")
	r.ThirdTransactionNo = field.NewString(table, "third_transaction_no")
	r.Amount = field.NewInt64(table, "amount")
	r.Status = field.NewInt32(table, "status")

	r.fillFieldMap()

	return r
}

func (r *receiptPO) WithContext(ctx context.Context) *receiptPODo {
	return r.receiptPODo.WithContext(ctx)
}

func (r receiptPO) TableName() string { return r.receiptPODo.TableName() }

func (r receiptPO) Alias() string { return r.receiptPODo.Alias() }

func (r receiptPO) Columns(cols ...field.Expr) gen.Columns { return r.receiptPODo.Columns(cols...) }

func (r *receiptPO) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *receiptPO) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 8)
	r.fieldMap["id"] = r.ID
	r.fieldMap["create_time"] = r.CreateTime
	r.fieldMap["update_time"] = r.UpdateTime
	r.fieldMap["order_no"] = r.OrderNo
	r.fieldMap["method"] = r.Method
	r.fieldMap["third_transaction_no"] = r.ThirdTransactionNo
	r.fieldMap["amount"] = r.Amount
	r.fieldMap["status"] = r.Status
}

func (r receiptPO) clone(db *gorm.DB) receiptPO {
	r.receiptPODo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r receiptPO) replaceDB(db *gorm.DB) receiptPO {
	r.receiptPODo.ReplaceDB(db)
	return r
}

type receiptPODo struct{ gen.DO }

func (r receiptPODo) Debug() *receiptPODo {
	return r.withDO(r.DO.Debug())
}

func (r receiptPODo) WithContext(ctx context.Context) *receiptPODo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r receiptPODo) ReadDB() *receiptPODo {
	return r.Clauses(dbresolver.Read)
}

func (r receiptPODo) WriteDB() *receiptPODo {
	return r.Clauses(dbresolver.Write)
}

func (r receiptPODo) Session(config *gorm.Session) *receiptPODo {
	return r.withDO(r.DO.Session(config))
}

func (r receiptPODo) Clauses(conds ...clause.Expression) *receiptPODo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r receiptPODo) Returning(value interface{}, columns ...string) *receiptPODo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r receiptPODo) Not(conds ...gen.Condition) *receiptPODo {
	return r.withDO(r.DO.Not(conds...))
}

func (r receiptPODo) Or(conds ...gen.Condition) *receiptPODo {
	return r.withDO(r.DO.Or(conds...))
}

func (r receiptPODo) Select(conds ...field.Expr) *receiptPODo {
	return r.withDO(r.DO.Select(conds...))
}

func (r receiptPODo) Where(conds ...gen.Condition) *receiptPODo {
	return r.withDO(r.DO.Where(conds...))
}

func (r receiptPODo) Order(conds ...field.Expr) *receiptPODo {
	return r.withDO(r.DO.Order(conds...))
}

func (r receiptPODo) Distinct(cols ...field.Expr) *receiptPODo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r receiptPODo) Omit(cols ...field.Expr) *receiptPODo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r receiptPODo) Join(table schema.Tabler, on ...field.Expr) *receiptPODo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r receiptPODo) LeftJoin(table schema.Tabler, on ...field.Expr) *receiptPODo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r receiptPODo) RightJoin(table schema.Tabler, on ...field.Expr) *receiptPODo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r receiptPODo) Group(cols ...field.Expr) *receiptPODo {
	return r.withDO(r.DO.Group(cols...))
}

func (r receiptPODo) Having(conds ...gen.Condition) *receiptPODo {
	return r.withDO(r.DO.Having(conds...))
}

func (r receiptPODo) Limit(limit int) *receiptPODo {
	return r.withDO(r.DO.Limit(limit))
}

func (r receiptPODo) Offset(offset int) *receiptPODo {
	return r.withDO(r.DO.Offset(offset))
}

func (r receiptPODo) Scopes(funcs ...func(gen.Dao) gen.Dao) *receiptPODo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r receiptPODo) Unscoped() *receiptPODo {
	return r.withDO(r.DO.Unscoped())
}

func (r receiptPODo) Create(values ...*po.ReceiptPO) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r receiptPODo) CreateInBatches(values []*po.ReceiptPO, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r receiptPODo) Save(values ...*po.ReceiptPO) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r receiptPODo) First() (*po.ReceiptPO, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*po.ReceiptPO), nil
	}
}

func (r receiptPODo) Take() (*po.ReceiptPO, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*po.ReceiptPO), nil
	}
}

func (r receiptPODo) Last() (*po.ReceiptPO, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*po.ReceiptPO), nil
	}
}

func (r receiptPODo) Find() ([]*po.ReceiptPO, error) {
	result, err := r.DO.Find()
	return result.([]*po.ReceiptPO), err
}

func (r receiptPODo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.ReceiptPO, err error) {
	buf := make([]*po.ReceiptPO, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r receiptPODo) FindInBatches(result *[]*po.ReceiptPO, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r receiptPODo) Attrs(attrs ...field.AssignExpr) *receiptPODo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r receiptPODo) Assign(attrs ...field.AssignExpr) *receiptPODo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r receiptPODo) Joins(fields ...field.RelationField) *receiptPODo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r receiptPODo) Preload(fields ...field.RelationField) *receiptPODo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r receiptPODo) FirstOrInit() (*po.ReceiptPO, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*po.ReceiptPO), nil
	}
}

func (r receiptPODo) FirstOrCreate() (*po.ReceiptPO, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*po.ReceiptPO), nil
	}
}

func (r receiptPODo) FindByPage(offset int, limit int) (result []*po.ReceiptPO, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r receiptPODo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r receiptPODo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r receiptPODo) Delete(models ...*po.ReceiptPO) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *receiptPODo) withDO(do gen.Dao) *receiptPODo {
	r.DO = *do.(*gen.DO)
	return r
}
