// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameColumnDO = "scm_column"

// ColumnDO 专栏表
type ColumnDO struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                          // 主键
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	Name       string    `gorm:"column:name;not null;comment:专栏名称" json:"name"`                                         // 专栏名称
	AuthorID   int64     `gorm:"column:author_id;not null;comment:作者id" json:"author_id"`                               // 作者id
	Status     int32     `gorm:"column:status;not null;comment:状态 NEW/OK/DISABLED 未发布/已生效/已禁用" json:"status"`           // 状态 NEW/OK/DISABLED 未发布/已生效/已禁用
}

// TableName ColumnDO's table name
func (*ColumnDO) TableName() string {
	return TableNameColumnDO
}
