// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

import (
	"time"
)

const TableNameColumnQuotePO = "scm_column_quote"

// ColumnQuotePO 专栏报价表
type ColumnQuotePO struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                          // 主键
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	ColumnID   int64     `gorm:"column:column_id;not null;comment:专栏id" json:"column_id"`                               // 专栏id
	EditorID   int64     `gorm:"column:editor_id;not null;comment:编辑id" json:"editor_id"`                               // 编辑id
	Price      int64     `gorm:"column:price;not null;comment:价格（单位：分）" json:"price"`                                   // 价格（单位：分）
	Status     int32     `gorm:"column:status;not null;comment:报价状态 0/1  未生效/已生效" json:"status"`                        // 报价状态 0/1  未生效/已生效
}

// TableName ColumnQuotePO's table name
func (*ColumnQuotePO) TableName() string {
	return TableNameColumnQuotePO
}
