// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

import (
	"time"
)

const TableNameCommissionPO = "scm_commission"

// CommissionPO 佣金表
type CommissionPO struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                          // 主键
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	Name        string    `gorm:"column:name;not null;comment:名称" json:"name"`                                           // 名称
	Amount      int64     `gorm:"column:amount;not null;comment:金额(单位：分)" json:"amount"`                                 // 金额(单位：分)
	ContractID  int64     `gorm:"column:contract_id;not null;comment:合同id" json:"contract_id"`                           // 合同id
	AuthorID    int64     `gorm:"column:author_id;not null;comment:作者id" json:"author_id"`                               // 作者id
	ReceiptID   int64     `gorm:"column:receipt_id;not null;comment:收款单id" json:"receipt_id"`                            // 收款单id
	PaymentDays string    `gorm:"column:payment_days;not null;comment:账期" json:"payment_days"`                           // 账期
	Status      int32     `gorm:"column:status;not null;comment:状态 0/1/2/3 未收款/已收款/已取消/已关闭" json:"status"`               // 状态 0/1/2/3 未收款/已收款/已取消/已关闭
}

// TableName CommissionPO's table name
func (*CommissionPO) TableName() string {
	return TableNameCommissionPO
}
