// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/eyebluecn/sc-misc/src/model/po"
)

func newCommissionPO(db *gorm.DB, opts ...gen.DOOption) commissionPO {
	_commissionPO := commissionPO{}

	_commissionPO.commissionPODo.UseDB(db, opts...)
	_commissionPO.commissionPODo.UseModel(&po.CommissionPO{})

	tableName := _commissionPO.commissionPODo.TableName()
	_commissionPO.ALL = field.NewAsterisk(tableName)
	_commissionPO.ID = field.NewInt64(tableName, "id")
	_commissionPO.CreateTime = field.NewTime(tableName, "create_time")
	_commissionPO.UpdateTime = field.NewTime(tableName, "update_time")
	_commissionPO.Name = field.NewString(tableName, "name")
	_commissionPO.Amount = field.NewInt64(tableName, "amount")
	_commissionPO.ContractID = field.NewInt64(tableName, "contract_id")
	_commissionPO.AuthorID = field.NewInt64(tableName, "author_id")
	_commissionPO.ReceiptID = field.NewInt64(tableName, "receipt_id")
	_commissionPO.PaymentDays = field.NewString(tableName, "payment_days")
	_commissionPO.Status = field.NewInt32(tableName, "status")

	_commissionPO.fillFieldMap()

	return _commissionPO
}

// commissionPO 佣金表
type commissionPO struct {
	commissionPODo commissionPODo

	ALL         field.Asterisk
	ID          field.Int64  // 主键
	CreateTime  field.Time   // 创建时间
	UpdateTime  field.Time   // 更新时间
	Name        field.String // 名称
	Amount      field.Int64  // 金额(单位：分)
	ContractID  field.Int64  // 合同id
	AuthorID    field.Int64  // 作者id
	ReceiptID   field.Int64  // 收款单id
	PaymentDays field.String // 账期
	Status      field.Int32  // 状态 0/1/2/3 未收款/已收款/已取消/已关闭

	fieldMap map[string]field.Expr
}

func (c commissionPO) Table(newTableName string) *commissionPO {
	c.commissionPODo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c commissionPO) As(alias string) *commissionPO {
	c.commissionPODo.DO = *(c.commissionPODo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *commissionPO) updateTableName(table string) *commissionPO {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateTime = field.NewTime(table, "update_time")
	c.Name = field.NewString(table, "name")
	c.Amount = field.NewInt64(table, "amount")
	c.ContractID = field.NewInt64(table, "contract_id")
	c.AuthorID = field.NewInt64(table, "author_id")
	c.ReceiptID = field.NewInt64(table, "receipt_id")
	c.PaymentDays = field.NewString(table, "payment_days")
	c.Status = field.NewInt32(table, "status")

	c.fillFieldMap()

	return c
}

func (c *commissionPO) WithContext(ctx context.Context) *commissionPODo {
	return c.commissionPODo.WithContext(ctx)
}

func (c commissionPO) TableName() string { return c.commissionPODo.TableName() }

func (c commissionPO) Alias() string { return c.commissionPODo.Alias() }

func (c commissionPO) Columns(cols ...field.Expr) gen.Columns {
	return c.commissionPODo.Columns(cols...)
}

func (c *commissionPO) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *commissionPO) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 10)
	c.fieldMap["id"] = c.ID
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_time"] = c.UpdateTime
	c.fieldMap["name"] = c.Name
	c.fieldMap["amount"] = c.Amount
	c.fieldMap["contract_id"] = c.ContractID
	c.fieldMap["author_id"] = c.AuthorID
	c.fieldMap["receipt_id"] = c.ReceiptID
	c.fieldMap["payment_days"] = c.PaymentDays
	c.fieldMap["status"] = c.Status
}

func (c commissionPO) clone(db *gorm.DB) commissionPO {
	c.commissionPODo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c commissionPO) replaceDB(db *gorm.DB) commissionPO {
	c.commissionPODo.ReplaceDB(db)
	return c
}

type commissionPODo struct{ gen.DO }

func (c commissionPODo) Debug() *commissionPODo {
	return c.withDO(c.DO.Debug())
}

func (c commissionPODo) WithContext(ctx context.Context) *commissionPODo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c commissionPODo) ReadDB() *commissionPODo {
	return c.Clauses(dbresolver.Read)
}

func (c commissionPODo) WriteDB() *commissionPODo {
	return c.Clauses(dbresolver.Write)
}

func (c commissionPODo) Session(config *gorm.Session) *commissionPODo {
	return c.withDO(c.DO.Session(config))
}

func (c commissionPODo) Clauses(conds ...clause.Expression) *commissionPODo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c commissionPODo) Returning(value interface{}, columns ...string) *commissionPODo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c commissionPODo) Not(conds ...gen.Condition) *commissionPODo {
	return c.withDO(c.DO.Not(conds...))
}

func (c commissionPODo) Or(conds ...gen.Condition) *commissionPODo {
	return c.withDO(c.DO.Or(conds...))
}

func (c commissionPODo) Select(conds ...field.Expr) *commissionPODo {
	return c.withDO(c.DO.Select(conds...))
}

func (c commissionPODo) Where(conds ...gen.Condition) *commissionPODo {
	return c.withDO(c.DO.Where(conds...))
}

func (c commissionPODo) Order(conds ...field.Expr) *commissionPODo {
	return c.withDO(c.DO.Order(conds...))
}

func (c commissionPODo) Distinct(cols ...field.Expr) *commissionPODo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c commissionPODo) Omit(cols ...field.Expr) *commissionPODo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c commissionPODo) Join(table schema.Tabler, on ...field.Expr) *commissionPODo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c commissionPODo) LeftJoin(table schema.Tabler, on ...field.Expr) *commissionPODo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c commissionPODo) RightJoin(table schema.Tabler, on ...field.Expr) *commissionPODo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c commissionPODo) Group(cols ...field.Expr) *commissionPODo {
	return c.withDO(c.DO.Group(cols...))
}

func (c commissionPODo) Having(conds ...gen.Condition) *commissionPODo {
	return c.withDO(c.DO.Having(conds...))
}

func (c commissionPODo) Limit(limit int) *commissionPODo {
	return c.withDO(c.DO.Limit(limit))
}

func (c commissionPODo) Offset(offset int) *commissionPODo {
	return c.withDO(c.DO.Offset(offset))
}

func (c commissionPODo) Scopes(funcs ...func(gen.Dao) gen.Dao) *commissionPODo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c commissionPODo) Unscoped() *commissionPODo {
	return c.withDO(c.DO.Unscoped())
}

func (c commissionPODo) Create(values ...*po.CommissionPO) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c commissionPODo) CreateInBatches(values []*po.CommissionPO, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c commissionPODo) Save(values ...*po.CommissionPO) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c commissionPODo) First() (*po.CommissionPO, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*po.CommissionPO), nil
	}
}

func (c commissionPODo) Take() (*po.CommissionPO, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*po.CommissionPO), nil
	}
}

func (c commissionPODo) Last() (*po.CommissionPO, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*po.CommissionPO), nil
	}
}

func (c commissionPODo) Find() ([]*po.CommissionPO, error) {
	result, err := c.DO.Find()
	return result.([]*po.CommissionPO), err
}

func (c commissionPODo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.CommissionPO, err error) {
	buf := make([]*po.CommissionPO, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c commissionPODo) FindInBatches(result *[]*po.CommissionPO, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c commissionPODo) Attrs(attrs ...field.AssignExpr) *commissionPODo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c commissionPODo) Assign(attrs ...field.AssignExpr) *commissionPODo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c commissionPODo) Joins(fields ...field.RelationField) *commissionPODo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c commissionPODo) Preload(fields ...field.RelationField) *commissionPODo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c commissionPODo) FirstOrInit() (*po.CommissionPO, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*po.CommissionPO), nil
	}
}

func (c commissionPODo) FirstOrCreate() (*po.CommissionPO, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*po.CommissionPO), nil
	}
}

func (c commissionPODo) FindByPage(offset int, limit int) (result []*po.CommissionPO, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c commissionPODo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c commissionPODo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c commissionPODo) Delete(models ...*po.CommissionPO) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *commissionPODo) withDO(do gen.Dao) *commissionPODo {
	c.DO = *do.(*gen.DO)
	return c
}
